const STORAGE_KEY='totto-blog-assistant-v3';
const $=id=>document.getElementById(id), pid=n=>`step${n}-prompt`, aid=n=>`step${n}-answer`;
const val=n=>$(aid(n))?.value.trim()||'';
let articleTheme='';
const themeError='現在の記事テーマと本文HTMLの内容が違う可能性があります。今回作成した本文HTMLをSTEP3回答欄に貼り付けてください。';
const steps=[['キーワード・検索ニーズ作成','キーワード候補5つと、検索ニーズ10個を一度に作成します。'],['見出し構成作成','STEP1の回答をもとに、記事の見出し構成を作成します。'],['本文HTML作成','STEP1・STEP2の回答をもとに、本文HTMLを作成します。'],['メタディスクリプション・タグ作成','本文HTMLをもとに、メタディスクリプションとWordPress用タグを作成します。'],['画像作成','アイキャッチ画像1枚と、H2下画像3枚を作成します。画像を作成したら、WordPressのメディアへ手動で追加してください。その後、取得した画像URLをSTEP6に入力します。']];
function h2s(html){return [...html.matchAll(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi)].map(x=>x[1].replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim()).filter(x=>x&&x!=='まとめ');}
function articleError(forImages=false){const a=val(3),t=$('theme').value.trim();if(!a)return 'STEP3でChatGPTから返ってきた本文HTMLを先に貼り付けてください。';if(!/<article\b[^>]*>/i.test(a))return 'STEP3回答欄には、<article>から始まる本文HTMLを貼り付けてください。';if(articleTheme&&t&&articleTheme!==t)return themeError;const words=t.replace(/[「」『』、】【・]/g,' ').split(/[\s　とがのはにを関係]/).filter(x=>x.length>=2);if(words.length&&!words.some(x=>a.includes(x)))return themeError;if(forImages){const headings=h2s(a);if(headings.length<3)return 'STEP3回答欄には、「まとめ」以外のH2見出しが3つ以上必要です。';}return '';}
function warn(n,s){$(`warning-${n}`).textContent=s;}
function render(){const flow=steps.map(([name,desc],i)=>{const n=i+1,label=n===1?'ChatGPTから返ってきた「キーワード候補・検索ニーズ」を貼り付ける欄':'ChatGPTの回答を貼り付ける欄';return `<details class="step" ${n===1?'open':''} id="step-${n}"><summary><span class="step-number">STEP ${n}</span><strong class="step-title">${name}</strong><span class="step-status" id="status-${n}">状態：未作成</span></summary><div class="step-body"><p class="hint">${desc}</p><p id="warning-${n}" class="step-warning" aria-live="polite"></p><div class="prompt-field"><label>ChatGPTに貼り付けるプロンプト<textarea class="prompt-textarea" id="${pid(n)}" readonly></textarea></label><button type="button" class="copy-button" data-copy="${pid(n)}" data-message="copy-message-${n}">このプロンプトをコピー</button><p class="field-message" id="copy-message-${n}" aria-live="polite"></p></div><div class="answer-field"><label>${label}<textarea class="answer-textarea" id="${aid(n)}" data-save="answer" placeholder="ChatGPTの回答をここに貼り付け"></textarea></label><p class="field-message" id="answer-message-${n}" aria-live="polite"></p></div></div></details>`;}).join('');$('workflow').innerHTML=flow+`<details class="step" id="step-6"><summary><span class="step-number">STEP 6</span><strong class="step-title">画像URL挿入・完成HTML作成</strong><span class="step-status" id="status-6">状態：未作成</span></summary><div class="step-body"><p class="hint">WordPressメディアの画像URLを入れて完成HTMLを作成します。画像の挿入先はSTEP3のH2から自動表示されます。</p><p id="warning-6" class="step-warning" aria-live="polite"></p><div id="imageUrlFields"></div><button type="button" class="primary" id="insertImages">画像URLを挿入して完成HTMLを作成</button><p class="field-message" id="final-message" aria-live="polite"></p><label>完成HTML<textarea class="large-textarea" id="finalHtml" readonly wrap="soft"></textarea></label><button type="button" class="copy-button" id="copyFinal" data-message="final-message">完成HTMLをコピー</button></div></details>`;}
function set(n,text,error=''){warn(n,error);$(pid(n)).value=error?'':text;}
function urlsComplete(){return ['h2Image1','h2Image2','h2Image3'].every(id=>$(id)?.value.trim());}
function setStatus(n,done,label){const status=$(`status-${n}`);if(!status)return;status.textContent=`状態：${label||(done?'回答貼り付け済み':'未作成')}`;status.classList.toggle('is-done',done);}
function updateStatuses(){for(let n=1;n<=5;n++)setStatus(n,!!val(n));const complete=!!$('finalHtml')?.value.trim();setStatus(6,complete,complete?'完成HTML作成済み':urlsComplete()?'画像URL入力済み':'未作成');}
function updateImageUrlFields(){const fields=$('imageUrlFields');if(!fields)return;const old=['h2Image1','h2Image2','h2Image3'].map(id=>$(id)?.value||'');const headings=h2s(val(3)).slice(0,3);fields.innerHTML=[0,1,2].map(i=>`<div class="url-field"><label>画像${['①','②','③'][i]}URL<input id="h2Image${i+1}" data-save="field" inputmode="url" placeholder="https://..."></label><p class="url-target">挿入先：${headings[i]?`H2「${headings[i]}」の直下`:'STEP3の本文HTMLからH2を取得すると表示されます'}</p></div>`).join('');old.forEach((value,i)=>{$(`h2Image${i+1}`).value=value;});}
function update(){const t=$('theme').value.trim()||'〇〇',a1=val(1),a2=val(2),a3=val(3),e3=!a1?'STEP1の回答を先に貼り付けてください。':!a2?'STEP2の見出し構成回答を先に貼り付けてください。':'';
set(1,`こんにちは！ あなたは自律神経症状専門の整体師です。\n\n「${t}」で検索されやすい内容を作成してください。\n\n【出力形式】\n【キーワード候補】\n1.\n2.\n3.\n4.\n5.\n\n【検索ニーズ】\n1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.\n9.\n10.\n\n検索ニーズは必ず「〜たい」で終わらせ、説明や分類は不要です。`);
set(2,`あなたはプロのWebライターです。以下のSTEP1回答だけを根拠に見出し構成を作成してください。\n\n【STEP1の回答：キーワード候補・検索ニーズ】\n${a1}\n\n仮タイトル、リード文、大見出し・小見出し・本文、まとめの順で出力してください。`,a1?'':'STEP1の回答欄に、キーワード候補・検索ニーズを貼り付けてください。');
set(3,`あなたは自律神経症状専門の整体師でプロのWebライターです。\n\n【記事テーマ】\n${t}\n【STEP1の回答】\n${a1}\n【STEP2の回答：見出し構成】\n${a2}\n\n見出し構成通りに3000字前後の本文を作成してください。本文HTMLは<article>から</article>までを1つのhtmlコードブロックに入れてください。おすすめタイトル5つと最もおすすめのタイトルは、本文HTMLと別のコードブロック外に出してください。`,e3);
const e4=!a1?'STEP1の回答を先に貼り付けてください。':articleError();set(4,`あなたはプロのWebライターです。\n\n【記事テーマ】\n${t}\n【STEP1の回答：キーワード候補・検索ニーズ】\n${a1}\n【STEP3の回答：今回作った記事本文】\n${a3}\n\n【出力形式】\n【メタディスクリプション】\n70〜120文字程度。誰に向けたどんな記事か、ベネフィットとキーワードを自然に含める。\n\n【タグ】\nWordPress用タグを5〜8個、カンマ区切りで出力する。`,e4);
const e5=articleError(true), hs=h2s(a3).slice(0,3), targets=hs.map((x,i)=>`・画像${['①','②','③'][i]}：H2「${x}」下の画像`).join('\n');set(5,`こんにちは！ あなたは自律神経症状専門の整体師です。\n\n今回の記事本文に合う画像を合計4枚作成してください。\n\n【重要】\n画像は合計4枚必要ですが、1枚の画像の中に4枚分を入れないでください。\nコラージュ画像にしないでください。\n分割画面にしないでください。\n4分割にしないでください。\n横に並べないでください。\n縦に並べないでください。\n1つの画像の中に複数場面を入れないでください。\nアイキャッチ画像、画像①、画像②、画像③は、それぞれ別々の独立した画像として作成してください。\nChatGPTでは、画像を1枚ずつ順番に生成してください。\n\n【記事テーマ】\n${t}\n\n【今回作った記事本文】\n${a3}\n\n【作成する画像】\n・アイキャッチ画像：記事全体の内容に合う画像\n${targets}\n\nH2「まとめ」用の画像は作成しないでください。\n\n【画像ごとの方向性】\nアイキャッチ画像：記事全体の悩み・原因・改善の方向性が自然に伝わる画像。\n画像①：H2「${hs[0]||''}」の内容に合わせ、原因・悩み・症状に気づいている場面。\n画像②：H2「${hs[1]||''}」の内容に合わせ、本文内容に合う自律神経・緊張・呼吸・休息・生活リズムなどの場面。\n画像③：H2「${hs[2]||''}」の内容に合わせ、改善方法・セルフケア・生活習慣・軽い運動・リラックス・予防行動などの場面。本文に合わせて自然に調整してください。\n\n【共通条件】\n・文字入れなし\n・図解なし\n・医療説明イラストなし\n・過度に医療的な機器を強調しない\n・人物と背景だけのシンプルな画像\n・安心感のある自然な雰囲気\n・ブログに使いやすい横長16:9\n・30〜50代の日本人女性を基本にする\n・清潔感のある明るい室内を基本にする\n・症状を大げさに表現しない\n・不安や苦痛を強調しすぎない\n・1枚につき1場面だけ\n・コラージュ禁止\n・分割画面禁止\n・複数画像を1枚にまとめることは禁止\n\n【最重要】\n4枚を1枚にまとめないでください。アイキャッチ画像、画像①、画像②、画像③を、それぞれ別々の独立した画像として作成してください。`,e5);}
function save(show=false){const d={answers:{},fields:{},meta:{articleTheme}};document.querySelectorAll('[data-save]').forEach(x=>(x.dataset.save==='answer'?d.answers:d.fields)[x.id]=x.value);d.fields.finalHtml=$('finalHtml')?.value||'';localStorage.setItem(STORAGE_KEY,JSON.stringify(d));if(show)$('saveMessage').textContent='この端末に保存しました。';}
function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');[d.answers,d.fields].filter(Boolean).forEach(g=>Object.entries(g).forEach(([k,v])=>{if($(k))$(k).value=v;}));articleTheme=d.meta?.articleTheme||'';}catch(_){}}
function imageInsert(){const e=articleError();if(e){warn(6,e);return;}if(!urlsComplete()){warn(6,'画像①〜③のURLをすべて入力してください。');return;}const urls=['h2Image1','h2Image2','h2Image3'].map(x=>$(x).value.trim());let i=0;$('finalHtml').value=val(3).replace(/<h2\b[^>]*>[\s\S]*?<\/h2>/gi,h=>{const title=h.replace(/<[^>]*>/g,'').trim(),u=title==='まとめ'?'':urls[i++];return u?`${h}\n<img src="${u.replace(/"/g,'&quot;')}" alt="${title.replace(/"/g,'&quot;')}" style="width:100%;height:auto;display:block;margin:24px 0;" loading="lazy">`:h;});warn(6,'');$('final-message').textContent='完成HTMLを作成しました。下のボタンでコピーできます。';updateStatuses();save();$('finalHtml').scrollIntoView({behavior:'smooth',block:'start'});}
async function copy(id,messageId){const target=$(id),message=$(messageId);if(!target?.value){if(message)message.textContent='コピーする内容がありません。';return;}try{await navigator.clipboard.writeText(target.value);}catch(_){target.focus();target.select();document.execCommand('copy');target.setSelectionRange(0,0);}if(message)message.textContent='コピーしました。';}
render();updateImageUrlFields();load();update();updateImageUrlFields();updateStatuses();document.addEventListener('input',e=>{if(!e.target.matches('[data-save],#theme,#reader,#notes'))return;const isStep3=e.target.id===aid(3);if(isStep3){articleTheme=$('theme').value.trim();$('finalHtml').value='';}if(e.target.matches('[data-save="answer"]')){const n=e.target.id.match(/step(\d+)-answer/)?.[1];if(n)$(`answer-message-${n}`).textContent='回答を保存しました。';}if(e.target.id.startsWith('h2Image'))$('finalHtml').value='';update();if(isStep3)updateImageUrlFields();updateStatuses();save();});document.addEventListener('click',e=>{if(e.target.dataset.copy)copy(e.target.dataset.copy,e.target.dataset.message);if(e.target.id==='insertImages')imageInsert();if(e.target.id==='copyFinal')copy('finalHtml','final-message');});$('saveNow').addEventListener('click',()=>save(true));$('clearAll').addEventListener('click',()=>{if(confirm('保存した入力内容をすべて消去しますか？')){localStorage.removeItem(STORAGE_KEY);location.reload();}});

// GitHub Pagesでも、読み込み済みの画面をオフラインで再表示できるようにする。
if('serviceWorker' in navigator&&location.protocol!=='file:'){
  window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
}

// うえむら整体院HPブログは、既存6STEPとは完全に別の保存領域・DOMを使う。
const CLINIC_STORAGE_KEY='uemura-clinic-hp-blog-v1';
const clinicSteps=[
  ['おすすめタイトル作成','元テーマ・病名から、患者さんに伝わりやすい投稿タイトルを選びます。'],
  ['記事一式作成','採用タイトルをもとに、WordPressに必要な記事一式を作成します。'],
  ['アイキャッチ画像作成','完成記事に合う、横長のアイキャッチ画像を作成します。']
];
const clinicEl=id=>document.getElementById(id);
const clinicValue=id=>clinicEl(id)?.value.trim()||'';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function clinicPrompt(n){ return clinicEl(`clinic-step${n}-prompt`); }
function clinicAnswer(n){ return clinicEl(`clinic-step${n}-answer`); }
function clinicStatus(n,done,label){const e=clinicEl(`clinic-status-${n}`);if(!e)return;e.textContent=`状態：${label||(done?'回答貼り付け済み':'未作成')}`;e.classList.toggle('is-done',done);}
function clinicNotice(n,text=''){const e=clinicEl(`clinic-warning-${n}`);if(e)e.textContent=text;}
function renderClinic(){
  clinicEl('clinicWorkflow').innerHTML=clinicSteps.map(([name,desc],i)=>{const n=i+1;let extra='';
    if(n===1)extra='<div class="answer-field"><label>元テーマ・病名<input id="clinic-theme" data-clinic-save placeholder="例：甲状腺機能低下症に伴う自律神経症状"></label></div>';
    if(n===2)extra='<div class="answer-field"><label>最終的に採用した投稿タイトル<input id="clinic-title" data-clinic-save placeholder="STEP1から選んだタイトルを入力"></label><p class="hint">STEP1の回答はプロンプトに自動で反映されます。</p></div>';
    return `<details class="step" ${n===1?'open':''}><summary><span class="step-number">STEP ${n}</span><strong class="step-title">${name}</strong><span class="step-status" id="clinic-status-${n}">状態：未作成</span></summary><div class="step-body"><p class="hint">${desc}</p><p id="clinic-warning-${n}" class="step-warning" aria-live="polite"></p>${extra}<div class="prompt-field"><label>ChatGPTに貼り付けるプロンプト<textarea class="prompt-textarea" id="clinic-step${n}-prompt" readonly></textarea></label><button type="button" class="copy-button" data-clinic-copy="clinic-step${n}-prompt" data-clinic-message="clinic-copy-${n}">プロンプトをコピー</button><p class="field-message" id="clinic-copy-${n}" aria-live="polite"></p></div><div class="answer-field"><label>ChatGPTの回答を貼り付ける欄<textarea class="answer-textarea" id="clinic-step${n}-answer" data-clinic-save placeholder="ChatGPTの回答をここに貼り付け"></textarea></label><button type="button" class="secondary clinic-answer-save" data-clinic-answer-save="${n}">回答を保存</button><p class="field-message" id="clinic-answer-message-${n}" aria-live="polite"></p></div></div></details>`;
  }).join('');
}
function clinicUpdate(){
  const theme=clinicValue('clinic-theme')||'〇〇';
  const answer1=clinicValue('clinic-step1-answer');
  const title=clinicValue('clinic-title');
  const answer2=clinicValue('clinic-step2-answer');
  clinicPrompt(1).value=`あなたは「うえむら整体院」の自律神経ブログを作成するプロのWebライターです。\n\n以下の元テーマ・病名から、おすすめ投稿タイトルを複数提案してください。\n\n【元テーマ・病名】\n${theme}\n\n【タイトルの条件】\n・一般の患者さんが見て分かりやすい\n・短い\n・検索されやすい\n・「自分の症状かもしれない」と感じやすい\n・必要以上に長くしない\n・元テーマと意味を変えない\n・病名そのものが一般的で検索需要もある場合は、無理に症状名へ変更しない\n\nおすすめタイトル候補を複数提示し、\n最後に「最もおすすめ」を1つ提示してください。\n\n記事本文・パーマリンク・タグなどはまだ作成しないでください。`;
  const step2Warning=!answer1?'STEP1のChatGPT回答を貼り付けてください。':!title?'最終的に採用した投稿タイトルを入力してください。':'';
  clinicNotice(2,step2Warning);
  clinicPrompt(2).value=step2Warning?'':`あなたは「うえむら整体院」の自律神経ブログを作成するプロのWebライターです。医学的正確性を最優先し、一般の患者さんにわかりやすい記事を作成してください。\n\n【STEP1のタイトル候補・回答】\n${answer1}\n\n【最終的に採用した投稿タイトル】\n${title}\n\n以下を必ず、順番を一切変えずに作成してください。各項目の内容は必ず個別のコードブロックに入れてください。説明文や項目の追加は不要です。\n\n### パーマリンク\n\`\`\`text\n英小文字・ハイフン形式。\n\`\`\`\n\n### カテゴリ\n\`\`\`text\n次の12種類から必ず1つだけ選ぶ。新しいカテゴリは作らない。\n1. ホルモン・代謝・婦人科\n2. めまい・耳の症状\n3. 全身性・その他の自律神経症状\n4. 冷え・ほてり・汗・むくみ\n5. 動悸・血圧・失神\n6. 呼吸・胸の症状\n7. 排尿・泌尿器の悩み\n8. 疲労・ストレス・不安\n9. 睡眠の悩み\n10. 神経疾患に伴う自律神経障害\n11. 胃腸・お腹の不調\n12. 頭痛・目・のどの症状\n\`\`\`\n\n### タグ\n\`\`\`text\nWordPress用タグをカンマ区切りで。\n\`\`\`\n\n### 記事本文\n\`\`\`html\n<article style="max-width:780px;margin:0 auto;color:#222;font-size:16px;line-height:2.2;">\n…\n</article>\n\`\`\`\n\n### メタディスクリプション\n\`\`\`text\n記事内容を簡潔に説明し、投稿タイトル・主要キーワードを自然に含める。SEOキーワードを不自然に羅列しない。\n\`\`\`\n\n### フォーカスキーフレーズ\n\`\`\`text\n記事内容・検索意図・SEOに最も適したものを1つだけ。投稿タイトルと同一でなくてよい。\n\`\`\`\n\n【記事本文HTMLの必須要件】\n・2026年9月に作成した「耳管開放症」の記事構成・説明量を基準にし、簡略化しない。読者が「なぜその症状が起こるのか」を理解できる内容にする。\n・WordPress投稿タイトルと、記事冒頭のSEOタイトルは分ける。最初のH2は <h2 style="margin:2.5em 0 1em;line-height:1.6;"><strong>SEOタイトル</strong></h2> とし、病名／症状、代表的な悩み、自律神経との関係を自然に含める。\n・次のH2は <h2 style="margin:2.5em 0 1em;"><strong>この記事でわかること</strong></h2>。単なる箇条書きにせず、「何もしていないのに心臓がドキドキする」「以前より汗をかきやすくなった」などテーマに合う具体症状から始め、病気／症状の概要、身体で起きていること、自律神経との関係、記事で説明する内容まで説明する。\n・目次は危険レベルと受診の目安、症状チェック、原因と自律神経との関係、自宅でできる生活ケア、うえむら整体院でできること、まとめへリンクする。各H2のidは順に risk、check、cause、care、clinic、summary を使う。\n・「危険レベルと受診の目安」はテーマに応じて危険レベル（例：●●〇〇〇）を示し、原則3段階程度で説明する。各ボックスに必ず「状態：」「目安：」「行動：」を含め、重大な病気を自律神経の乱れとして片付けない。\n・「症状チェック」は10項目前後の <ul style="line-height:2.2;"> を使う。チェックリスト後に、特徴的な症状、他の病気との違い、症状だけでは診断できないことを説明する。\n・「原因と自律神経との関係」は中心部分として複数のH3を使う。「そもそも○○とは？」「身体では何が起こっている？」「原因1〜3」「なぜ○○が起こるの？」「自律神経とはどのような関係がある？」「ストレスとの関係」「どのように診断するの？」など、患者さんが抱きやすい疑問をテーマに合わせて使う。\n・医学的な病態がある疾患を何でも自律神経の乱れが原因とは説明しない。「自律神経の乱れが原因です」「自律神経を整えれば治ります」「整体で治ります」と断定しない。疾患そのものの医学的原因・病態を先に説明し、自律神経との関係は分けて説明する。必要に応じて「自律神経が乱れたことが○○の直接的な原因という意味ではありません」「この症状だけで○○と判断することはできません」「ほかの疾患でも同様の症状が起こることがあります」を入れる。\n・「自宅でできる生活ケア」は、医療機関で診断・治療が必要な疾患なら最初にそれを説明する。その後、テーマに合う具体的な生活ケアを8〜10項目程度示し、睡眠・食事・運動だけの一般論にしない。\n・「うえむら整体院でできること」の施設名は必ず「うえむら整体院」。病気そのものを診断・治療できる表現はしない。「○○は医療機関で診断・治療を受ける必要がある病気です」「うえむら整体院で○○そのものを診断・治療することはできません」を必要に応じて明記する。その上で睡眠、疲労、呼吸、姿勢、身体の緊張など身体面を確認することを書く。自然に合う場合は「自律神経が働きやすく、夜に深く眠り、一晩寝たらしっかり回復できる身体づくりをサポートします。」を使うが、「自律神経を整えれば○○が治るという意味ではありません」と線引きする。\n・「まとめ」は、どんな病気／症状か、代表的症状、主な原因や仕組み、自律神経との関係、受診すべきケースを簡潔に振り返り、読者が次に何をすればよいか分かる文章で終える。`;
  const step3Warning=!answer2?'STEP2の記事一式の回答を貼り付けてください。':!title?'採用タイトルを入力してください。':'';
  clinicNotice(3,step3Warning);
  clinicPrompt(3).value=step3Warning?'':`あなたは「うえむら整体院」の自律神経ブログのデザイナーです。以下の記事用に、アイキャッチ画像を1枚作成してください。\n\n【投稿タイトル】\n${title}\n\n【記事一式】\n${answer2}\n\n【画像の条件】\n・ブログに使いやすい横長16:9\n・文字入れなし、図解なし、コラージュ・分割画面なし\n・記事内容が自然に伝わる人物と背景だけのシンプルな1場面\n・30〜50代の日本人を基本に、清潔感と安心感のある自然な雰囲気\n・症状や苦痛を大げさに表現しない\n・過度に医療的な機器を強調しない`;
  clinicStatus(1,!!clinicValue('clinic-step1-answer'));
  clinicStatus(2,!!answer2);
  clinicStatus(3,!!clinicValue('clinic-step3-answer'));
}
function clinicSave(show=false){const data={theme:clinicEl('clinic-theme')?.value||'',title:clinicEl('clinic-title')?.value||'',answers:{1:clinicEl('clinic-step1-answer')?.value||'',2:clinicEl('clinic-step2-answer')?.value||'',3:clinicEl('clinic-step3-answer')?.value||''}};localStorage.setItem(CLINIC_STORAGE_KEY,JSON.stringify(data));if(show)clinicEl('clinicSaveMessage').textContent='うえむら整体院HPブログの内容をこの端末に保存しました。';}
function clinicLoad(){try{const d=JSON.parse(localStorage.getItem(CLINIC_STORAGE_KEY)||'{}');if(clinicEl('clinic-theme'))clinicEl('clinic-theme').value=d.theme||'';if(clinicEl('clinic-title'))clinicEl('clinic-title').value=d.title||'';Object.entries(d.answers||{}).forEach(([n,v])=>clinicAnswer(n).value=v||'');}catch(_){}}
function showBlog(kind){const director=kind==='director';clinicEl('directorBlog').hidden=!director;clinicEl('clinicBlog').hidden=director;document.querySelectorAll('.blog-switch').forEach(b=>{const active=b.dataset.blog===kind;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',active);});localStorage.setItem('totto-blog-assistant-active-blog',kind);}

renderClinic();clinicLoad();clinicUpdate();
document.querySelectorAll('.blog-switch').forEach(b=>b.addEventListener('click',()=>showBlog(b.dataset.blog)));
showBlog(localStorage.getItem('totto-blog-assistant-active-blog')||'director');
document.addEventListener('input',e=>{if(!e.target.matches('[data-clinic-save]'))return;clinicUpdate();clinicSave();});
document.addEventListener('click',e=>{const copyId=e.target.dataset.clinicCopy;if(copyId)copy(copyId,e.target.dataset.clinicMessage);const n=e.target.dataset.clinicAnswerSave;if(n){clinicSave();clinicEl(`clinic-answer-message-${n}`).textContent='回答を保存しました。';}if(e.target.id==='clinicSaveNow')clinicSave(true);if(e.target.id==='clinicClearAll'&&confirm('うえむら整体院HPブログの保存内容をすべて消去しますか？')){localStorage.removeItem(CLINIC_STORAGE_KEY);location.reload();}});
