const STORAGE_KEY='totto-blog-assistant-v3';
const $=id=>document.getElementById(id), pid=n=>`step${n}-prompt`, aid=n=>`step${n}-answer`;
const val=n=>$(aid(n))?.value.trim()||'';
let articleTheme='';
const themeError='現在の記事テーマと本文HTMLの内容が違う可能性があります。今回作成した本文HTMLをSTEP3回答欄に貼り付けてください。';
const steps=[['キーワード・検索ニーズ作成','キーワード候補5つと、検索ニーズ10個を一度に作成します。'],['見出し構成作成','STEP1の回答をもとに、記事の見出し構成を作成します。'],['本文HTML作成','STEP1・STEP2の回答をもとに、本文HTMLを作成します。'],['メタディスクリプション・タグ作成','本文HTMLをもとに、メタディスクリプションとWordPress用タグを作成します。'],['画像作成','アイキャッチ画像1枚と、H2下画像3枚を作成します。画像を作成したら、WordPressのメディアへ手動で追加してください。その後、取得した画像URLをSTEP6に入力します。']];
function h2s(html){return [...html.matchAll(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi)].map(x=>x[1].replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim()).filter(x=>x&&x!=='まとめ');}
function articleError(forImages=false){const a=val(3),t=$('theme').value.trim();if(!a)return 'STEP3でChatGPTから返ってきた本文HTMLを先に貼り付けてください。';if(!/<article\b[^>]*>/i.test(a))return 'STEP3回答欄には、<article>から始まる本文HTMLを貼り付けてください。';if(articleTheme&&t&&articleTheme!==t)return themeError;const words=t.replace(/[「」『』、】【・]/g,' ').split(/[\s　とがのはにを関係]/).filter(x=>x.length>=2);if(words.length&&!words.some(x=>a.includes(x)))return themeError;if(forImages){const headings=h2s(a);if(headings.length<3)return 'STEP3回答欄には、「まとめ」以外のH2見出しが3つ以上必要です。';}return '';}
function warn(n,s){$(`warning-${n}`).textContent=s;}
function render(){const flow=steps.map(([name,desc],i)=>{const n=i+1,label=n===1?'ChatGPTから返ってきた「キーワード候補・検索ニーズ」を貼り付ける欄':'ChatGPTの回答を貼り付ける欄';return `<details class="step" ${n===1?'open':''} id="step-${n}"><summary><span class="step-number">STEP ${n}</span><strong class="step-title">${name}</strong><span class="step-status" id="status-${n}">状態：未作成</span></summary><div class="step-body"><p class="hint">${desc}</p><p id="warning-${n}" class="step-warning" aria-live="polite"></p><div class="prompt-field"><label>ChatGPTに貼り付けるプロンプト<textarea class="prompt-textarea" id="${pid(n)}" readonly></textarea></label><button type="button" class="copy-button" data-copy="${pid(n)}" data-message="copy-message-${n}">このプロンプトをコピー</button><p class="field-message" id="copy-message-${n}" aria-live="polite"></p></div><div class="answer-field"><label>${label}<textarea class="answer-textarea" id="${aid(n)}" data-save="answer" placeholder="ChatGPTの回答をここに貼り付け"></textarea></label><p class="field-message" id="answer-message-${n}" aria-live="polite"></p></div></div></details>`;}).join('');$('workflow').innerHTML=flow+`<details class="step" id="step-6"><summary><span class="step-number">STEP 6</span><strong class="step-title">画像URL挿入・完成HTML作成</strong><span class="step-status" id="status-6">状態：未作成</span></summary><div class="step-body"><p class="hint">WordPressメディアの画像URLを入れて完成HTMLを作成します。画像の挿入先はSTEP3のH2から自動表示されます。</p><p id="warning-6" class="step-warning" aria-live="polite"></p><div id="imageUrlFields"></div><button type="button" class="primary" id="insertImages">画像URLを挿入して完成HTMLを作成</button><p class="field-message" id="final-message" aria-live="polite"></p><label>完成HTML<textarea class="large-textarea" id="finalHtml" readonly wrap="soft"></textarea></label><button type="button" class="copy-button" id="copyFinal" data-message="final-message">完成HTMLをコピー</button></div></details>`;}
function set(n,text,error=''){warn(n,error);$(pid(n)).value=error?'':text;}
function urlsComplete(){return ['h2Image1','h2Image2','h2Image3'].every(id=>$(id)?.value.trim());}
function setStatus(n,done,label){const status=$(`status-${n}`);if(!status)return;status.textContent=`状態：${label||(done?'回答貼り付け済み':'未作成')}`;status.classList.toggle('is-done',done);}
function updateStatuses(){for(let n=1;n<=5;n++)setStatus(n,!!val(n));const complete=!!$('finalHtml')?.value.trim();setStatus(6,complete,complete?'完成HTML作成済み':urlsComplete()?'画像URL入力済み':'未作成');}
function updateImageUrlFields(){const fields=$('imageUrlFields');if(!fields)return;const old=['h2Image1','h2Image2','h2Image3'].map(id=>$(id)?.value||'');const headings=h2s(val(3)).slice(0,3);fields.innerHTML=[0,1,2].map(i=>`<div class="url-field"><label>画像${['①','②','③'][i]}URL<input id="h2Image${i+1}" data-save="field" inputmode="url" placeholder="https://..."></label><p class="url-target">挿入先：${headings[i]?`H2「${headings[i]}」の直下`:'STEP3の本文HTMLからH2を取得すると表示されます'}</p></div>`).join('');old.forEach((value,i)=>{$(`h2Image${i+1}`).value=value;});}
function update(){const t=$('theme').value.trim()||'〇〇',a1=val(1),a2=val(2),a3=val(3),e3=!a1?'STEP1の回答を先に貼り付けてください。':!a2?'STEP2の見出し構成回答を先に貼り付けてください。':'';
set(1,`こんにちは！ あなたは自律神経症状専門の整体師です。\n\n「${t}」で検索されやすい内容を作成してください。\n\n【出力形式】\n【キーワード候補】\n1.\n2.\n3.\n4.\n5.\n\n【検索ニーズ】\n1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.\n9.\n10.\n\n検索ニーズは必ず「〜たい」で終わらせ、説明や分類は不要です。`);
set(2,`あなたはプロのWebライターです。以下のSTEP1回答だけを根拠に見出し構成を作成してください。\n\n【STEP1の回答：キーワード候補・検索ニーズ】\n${a1}\n\n仮タイトル、リード文、大見出し・小見出し・本文、まとめの順で出力してください。`,a1?'':'STEP1の回答欄に、キーワード候補・検索ニーズを貼り付けてください。');
set(3,`あなたは自律神経症状専門の整体師でプロのWebライターです。\n\n【記事テーマ】\n${t}\n【STEP1の回答】\n${a1}\n【STEP2の回答：見出し構成】\n${a2}\n\n見出し構成通りに3000字前後の本文を作成してください。本文HTMLは<article>から</article>までを1つのhtmlコードブロックに入れてください。おすすめタイトル5つと最もおすすめのタイトルは、本文HTMLと別のコードブロック外に出してください。`,e3);
const e4=!a1?'STEP1の回答を先に貼り付けてください。':articleError();set(4,`あなたはプロのWebライターです。\n\n【記事テーマ】\n${t}\n【STEP1の回答：キーワード候補・検索ニーズ】\n${a1}\n【STEP3の回答：今回作った記事本文】\n${a3}\n\n【出力形式】\n【メタディスクリプション】\n70〜120文字程度。誰に向けたどんな記事か、ベネフィットとキーワードを自然に含める。\n\n【タグ】\nWordPress用タグを5〜8個、カンマ区切りで出力する。`,e4);
const e5=articleError(true), hs=h2s(a3).slice(0,3), targets=hs.map((x,i)=>`・画像${['①','②','③'][i]}：H2「${x}」下の画像`).join('\n');set(5,`こんにちは！ あなたは自律神経症状専門の整体師です。\n\n今回の記事本文に合う画像を合計4枚作成してください。\n\n【重要】\n画像は合計4枚必要ですが、1枚の画像の中に4枚分を入れないでください。\nコラージュ画像にしないでください。\n分割画面にしないでください。\n4分割にしないでください。\n横に並べないでください。\n縦に並べないでください。\n1つの画像の中に複数場面を入れないでください。\nアイキャッチ画像、画像①、画像②、画像③は、それぞれ別々の独立した画像として作成してください。\nChatGPTでは、画像を1枚ずつ順番に生成してください。\n\n【記事テーマ】\n${t}\n\n【今回作った記事本文】\n${a3}\n\n【作成する画像】\n・アイキャッチ画像：記事全体の内容に合う画像\n${targets}\n\nH2「まとめ」用の画像は作成しないでください。\n\n【画像ごとの方向性】\nアイキャッチ画像：記事全体の悩み・原因・改善の方向性が自然に伝わる画像。\n画像①：H2「${hs[0]||''}」の内容に合わせ、原因・悩み・症状に気づいている場面。\n画像②：H2「${hs[1]||''}」の内容に合わせ、本文内容に合う自律神経・緊張・呼吸・休息・生活リズムなどの場面。\n画像③：H2「${hs[2]||''}」の内容に合わせ、改善方法・セルフケア・生活習慣・軽い運動・リラックス・予防行動などの場面。本文に合わせて自然に調整してください。\n\n【共通条件】\n・文字入れなし\n・図解なし\n・医療説明イラストなし\n・過度に医療的な機器を強調しない\n・人物と背景だけのシンプルな画像\n・安心感のある自然な雰囲気\n・ブログに使いやすい横長16:9\n・30〜50代の日本人女性を基本にする\n・清潔感のある明るい室内を基本にする\n・症状を大げさに表現しない\n・不安や苦痛を強調しすぎない\n・1枚につき1場面だけ\n・コラージュ禁止\n・分割画面禁止\n・複数画像を1枚にまとめることは禁止\n\n【最重要】\n4枚を1枚にまとめないでください。アイキャッチ画像、画像①、画像②、画像③を、それぞれ別々の独立した画像として作成してください。`,e5);}
function save(show=false){const d={answers:{},fields:{},meta:{articleTheme}};document.querySelectorAll('[data-save]').forEach(x=>(x.dataset.save==='answer'?d.answers:d.fields)[x.id]=x.value);d.fields.finalHtml=$('finalHtml')?.value||'';localStorage.setItem(STORAGE_KEY,JSON.stringify(d));if(show)$('saveMessage').textContent='この端末に保存しました。';}
function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');[d.answers,d.fields].filter(Boolean).forEach(g=>Object.entries(g).forEach(([k,v])=>{if($(k))$(k).value=v;}));articleTheme=d.meta?.articleTheme||'';}catch(_){}}
function imageInsert(){const e=articleError();if(e){warn(6,e);return;}if(!urlsComplete()){warn(6,'画像①〜③のURLをすべて入力してください。');return;}const urls=['h2Image1','h2Image2','h2Image3'].map(x=>$(x).value.trim());let i=0;$('finalHtml').value=val(3).replace(/<h2\b[^>]*>[\s\S]*?<\/h2>/gi,h=>{const title=h.replace(/<[^>]*>/g,'').trim(),u=title==='まとめ'?'':urls[i++];return u?`${h}\n<img src="${u.replace(/"/g,'&quot;')}" alt="${title.replace(/"/g,'&quot;')}" style="width:100%;height:auto;display:block;margin:24px 0;" loading="lazy">`:h;});warn(6,'');$('final-message').textContent='完成HTMLを作成しました。下のボタンでコピーできます。';updateStatuses();save();$('finalHtml').scrollIntoView({behavior:'smooth',block:'start'});}
async function copy(id,messageId){const target=$(id),message=$(messageId);if(!target?.value){if(message)message.textContent='コピーする内容がありません。';return;}try{await navigator.clipboard.writeText(target.value);}catch(_){target.focus();target.select();document.execCommand('copy');target.setSelectionRange(0,0);}if(message)message.textContent='コピーしました。';}
render();updateImageUrlFields();load();update();updateImageUrlFields();updateStatuses();document.addEventListener('input',e=>{if(!e.target.matches('[data-save],#theme,#reader,#notes'))return;const isStep3=e.target.id===aid(3);if(isStep3){articleTheme=$('theme').value.trim();$('finalHtml').value='';}if(e.target.matches('[data-save="answer"]')){const n=e.target.id.match(/step(\d+)-answer/)?.[1];if(n)$(`answer-message-${n}`).textContent='回答を保存しました。';}if(e.target.id.startsWith('h2Image'))$('finalHtml').value='';update();if(isStep3)updateImageUrlFields();updateStatuses();save();});document.addEventListener('click',e=>{if(e.target.dataset.copy)copy(e.target.dataset.copy,e.target.dataset.message);if(e.target.id==='insertImages')imageInsert();if(e.target.id==='copyFinal')copy('finalHtml','final-message');});$('saveNow').addEventListener('click',()=>save(true));$('clearAll').addEventListener('click',()=>{if(confirm('保存した入力内容をすべて消去しますか？')){localStorage.removeItem(STORAGE_KEY);location.reload();}});

// GitHub Pagesでも、読み込み済みの画面をオフラインで再表示できるようにする。
if('serviceWorker' in navigator&&location.protocol!=='file:'){
  window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
}
